/*Counts de todas las tablas*/
SELECT 'Actor' , COUNT(*) FROM ACTOR
UNION ALL
SELECT 'Categoria' , COUNT(*) FROM CATEGORIA
UNION ALL
SELECT 'Ciudad' , COUNT(*) FROM CIUDAD 
UNION ALL 
SELECT 'Clasificacion' , COUNT(*) FROM CLASIFICACION
UNION ALL
SELECT 'Cliente' , COUNT(*) FROM CLIENTE
UNION ALL
SELECT 'Empleado' , COUNT(*) FROM EMPLEADO 
UNION ALL
SELECT 'Encargado' , COUNT(*) FROM ENCARGADO 
UNION ALL 
SELECT 'Factura' , COUNT(*) FROM FACTURA
UNION ALL
SELECT 'Idioma' , COUNT(*) FROM IDIOMA 
UNION ALL 
SELECT 'Inventario' , COUNT(*) FROM INVENTARIO 
UNION ALL
SELECT 'Pais' , COUNT(*) FROM PAIS
UNION ALL
SELECT 'Pelicula' , COUNT(*) FROM PELICULA
UNION ALL 
SELECT 'Pelicula_Actor' , COUNT(*) FROM PELICULA_ACTOR 
UNION ALL 
SELECT 'Pelicula_Categoria' , COUNT(*) FROM PELICULA_CATEGORIA
UNION ALL
SELECT 'Pelicula_Idioma' , COUNT(*) FROM PELICULA_IDIOMA
UNION ALL
SELECT 'Tienda' , COUNT(*) FROM TIENDA; 