-- Insertar en Tabla Pais
INSERT INTO PAIS (Nombre)
SELECT DISTINCT t.PAIS_CLIENTE 
FROM TEMPORAL t 
WHERE t.PAIS_CLIENTE IS NOT NULL t.PAIS_CLIENTE  NOT IN (SELECT NOMBRE FROM PAIS p)
GROUP BY t.PAIS_CLIENTE;
            
INSERT INTO PAIS (Nombre)
SELECT DISTINCT TEMPORAL.PAIS_EMPLEADO 
FROM TEMPORAL 
WHERE TEMPORAL.PAIS_EMPLEADO IS NOT NULL AND TEMPORAL.PAIS_EMPLEADO  NOT IN (SELECT NOMBRE FROM PAIS p)
GROUP BY TEMPORAL.PAIS_EMPLEADO;
            
INSERT INTO PAIS (Nombre)
SELECT DISTINCT TEMPORAL.PAIS_TIENDA 
FROM TEMPORAL 
WHERE TEMPORAL.PAIS_TIENDA IS NOT NULL AND TEMPORAL.PAIS_TIENDA  NOT IN (SELECT NOMBRE FROM PAIS p)
GROUP BY TEMPORAL.PAIS_TIENDA;
             
COMMIT;

SELECT * FROM PAIS p;

-- Insertar en Tabla Ciudad
INSERT INTO CIUDAD (NOMBRE, CODIGO_POSTAL, PAIS)
SELECT DISTINCT t.CIUDAD_CLIENTE, t.CODIGO_POSTAL_CLIENTE , p.ID_PAIS 
FROM TEMPORAL t INNER JOIN PAIS p
ON t.PAIS_CLIENTE = p.NOMBRE 
WHERE t.CIUDAD_CLIENTE IS NOT NULL AND t.CODIGO_POSTAL_CLIENTE IS NOT NULL AND t.CIUDAD_CLIENTE NOT IN (SELECT c.NOMBRE FROM CIUDAD c GROUP BY c.NOMBRE);

INSERT INTO CIUDAD (NOMBRE, CODIGO_POSTAL, PAIS)
SELECT DISTINCT t.CIUDAD_EMPLEADO , t.CODIGO_POSTAL_EMPLEADO , p.ID_PAIS 
FROM TEMPORAL t INNER JOIN PAIS p
ON t.PAIS_EMPLEADO = p.NOMBRE 
WHERE t.CIUDAD_EMPLEADO IS NOT NULL AND t.CODIGO_POSTAL_EMPLEADO IS NOT NULL AND t.CIUDAD_EMPLEADO NOT IN (SELECT c.NOMBRE FROM CIUDAD c);

INSERT INTO CIUDAD (NOMBRE, CODIGO_POSTAL, PAIS)
SELECT DISTINCT t.CIUDAD_TIENDA , t.CODIGO_POSTAL_TIENDA, p.ID_PAIS 
FROM TEMPORAL t INNER JOIN PAIS p
ON t.PAIS_TIENDA = p.NOMBRE 
WHERE t.CIUDAD_TIENDA IS NOT NULL AND t.CODIGO_POSTAL_TIENDA IS NOT NULL AND t.CIUDAD_TIENDA NOT IN (SELECT c.NOMBRE FROM CIUDAD c);

COMMIT;

SELECT * FROM CIUDAD c ;


